module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VERIFY_USER: "VERIFY_USER",
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_RECEIVIED: "MESSAGE_RECEIVIED",
    TYPING: "TYPING",
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
}